-- CREATE TABLE Person(
--    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    username varchar(100) NOT NULL,
--    password varchar NOT NULL,
--    full_name varchar NOT NULL,
--    address varchar NOT NULL,
--    email varchar(100) NOT NULL,
--    number varchar(20) NOT NULL
-- );

-- CREATE TABLE Restaurant(
--        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--        name varchar(100) NOT NULL,
--        description varchar NOT NULL,
--        address varchar NOT NULL,
--        phone varchar NOT NULL
-- );

-- CREATE TABLE Seat_Reservation(
--     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     seat_number smallint NOT NULL,
--     capacity smallint NOT NULL,
--     description varchar,
--     restaurant_id int REFERENCES restaurant(id)
-- );


