CREATE TABLE Person(
   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   username varchar(100) NOT NULL,
   password varchar NOT NULL,
   full_name varchar NOT NULL,
   address varchar NOT NULL,
   email varchar(100) NOT NULL,
   number varchar(20) NOT NULL,
   role varchar(100) NOT NULL,
   created timestamp,
   updated timestamp,
   deleted boolean default false
);

CREATE TABLE Restaurant(
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name varchar(100) NOT NULL,
       description varchar NOT NULL,
       address varchar NOT NULL,
       phone varchar NOT NULL,
       created timestamp,
       updated timestamp,
       deleted boolean default false
);

CREATE TABLE Seat_Reservation(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_number smallint NOT NULL,
    capacity smallint NOT NULL,
    description varchar,
    restaurant_id int REFERENCES restaurant(id),
    created timestamp,
    updated timestamp,
    deleted boolean default false
);

CREATE TABLE Reservation(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    person_id int REFERENCES person(id) ON DELETE CASCADE,
    seat_reservation_id int REFERENCES seat_reservation(id) ON DELETE CASCADE,
    restaurant_id int REFERENCES restaurant(id) ON DELETE CASCADE,
    created timestamp,
    updated timestamp,
    deleted boolean default false
);
